@startuml Tabellenschema

skinparam Linetype ortho
object Usertabelle {

    id = INT PK 
    name = VARCHAR
    email = VARCHAR
    passwort = VARCHAR
    berechtigung = BOOL
}

object Produkttabelle {

    id = INT PK
    name = VARCHAR
    kategorie = INT FK
    steuersatz = INT FK
    preis = FLOAT
}

object Kategorientabelle {

    id = INT PK
    name = VARCHAR
}

object Steuersatztabelle{
    id = INT PK
    satz = INT
}

Kategorientabelle::id --> Produkttabelle::kategorie
Steuersatztabelle::id --> Produkttabelle::steuersatz

object Kundentabelle{
    id = INT PK
    name = VARCHAR
    email = VARCHAR
    
}

object Rechnungstabelle {
    id = INT PK
    datum = DATE
    kunde = INT FK
    verschickt = BOOL
    beglichen = BOOL
}

object Postentabelle {

    id = INT PK
    produkt_id = INT FK
    menge = INT
    rechnungs_id = INT FK
}

Kundentabelle::id --> Rechnungstabelle::kunde
Rechnungstabelle::id -->Postentabelle::rechnungs_id
Produkttabelle::id --> Postentabelle::produkt_id
@enduml